services:
  - type: web
    name: sutaba
    env: ruby
    buildCommand: bash -c "export SECRET_KEY_BASE=dummy_secret_key_base_for_asset_precompilation_only && bundle install && bundle exec rake assets:precompile"
    startCommand: bundle exec puma -C config/puma.rb
    preDeployCommand: bundle exec rails db:migrate
