services:
  - type: web
    name: sutaba
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    preDeployCommand: bundle exec rails db:migrate
