production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV.fetch("DATABASE_URL") { "postgresql://#{ENV['POSTGRES_USER']}:#{ENV['POSTGRES_PASSWORD']}@#{ENV['POSTGRES_HOST']}/#{ENV['POSTGRES_DB']}" } %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  cable:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV.fetch("DATABASE_URL") { "postgresql://#{ENV['POSTGRES_USER']}:#{ENV['POSTGRES_PASSWORD']}@#{ENV['POSTGRES_HOST']}/#{ENV['POSTGRES_DB']}" } %>
    pool: 5

  queue:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV.fetch("DATABASE_URL") { "postgresql://#{ENV['POSTGRES_USER']}:#{ENV['POSTGRES_PASSWORD']}@#{ENV['POSTGRES_HOST']}/#{ENV['POSTGRES_DB']}" } %>
    pool: 5

  cache:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV.fetch("DATABASE_URL") { "postgresql://#{ENV['POSTGRES_USER']}:#{ENV['POSTGRES_PASSWORD']}@#{ENV['POSTGRES_HOST']}/#{ENV['POSTGRES_DB']}" } %>
    pool: 5
